// <auto-generated />
namespace AleksandarMihaljev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class druga : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(druga));
        
        string IMigrationMetadata.Id
        {
            get { return "202112121826273_druga"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
